stm_bm(["vewgdhr",400,"","/menu/blank.gif",0,"","",1,0,0,0,50,1,0,0,""],this);
stm_bp("p0",[0,4,0,0,0,3,18,7,100,"",-2,"",-2,90,0,0,"#006699","transparent","",3,0,0,"#ffffff"]);
stm_ai("p0i0",[0,"  主页    ","","",-1,-1,0,"/SJTUoutdoor/freebag/xiehui/index.htm","_self","","","/menu/emblem.gif","/menu/emblem.gif",18,18,0,"","",0,0,0,0,1,"#ffffff",1,"#ffffff",1,"/menu/xp1.gif","/menu/xp2.gif",3,3,0,0,"#ffffff","#ffffff","#333333","#666666","bold 8pt Arial","bold 8pt Arial",0,0]);
stm_aix("p0i1","p0i0",[0,"    知识百科     ","","",-1,-1,0,"/SJTUoutdoor/freebag/knowledge/index.htm","_self","","","","",0,0,0,"/menu/arrow_r.gif","/menu/arrow_r.gif",7,7]);
stm_bp("p1",[1,4,0,0,0,3,0,0,100,"progid:DXImageTransform.Microsoft.Fade(overlap=.5,enabled=0,Duration=0.70)",-2,"progid:DXImageTransform.Microsoft.RadialWipe(wipeStyle=wedge,enabled=0,Duration=0.70)",-2,40,0,0,"#7f7f7f","transparent","",3,0,0,"#000000"]);
stm_aix("p1i0","p0i0",[0,"基本常识","","",-1,-1,0,"/SJTUoutdoor/freebag/knowledge/base/index.htm","_self","","","","",0,0,0,"","",0,0,0,0,1,"#ffffff",1,"#ffffff",1,"/menu/xp1.gif","/menu/xp2.gif",3,3,0,0,"#ffffff","#ffffff","#333333","#666666","8pt Arial","8pt Arial"]);
stm_aix("p1i1","p1i0",[0,"攀岩岩降","","",-1,-1,0,"/SJTUoutdoor/freebag/knowledge/rockcraft/index.htm"]);
stm_aix("p1i2","p1i0",[0,"定向越野","","",-1,-1,0,"/SJTUoutdoor/freebag/knowledge/orienteering/index.htm"]);
stm_aix("p1i3","p1i0",[0,"登山","","",-1,-1,0,"/SJTUoutdoor/freebag/knowledge/mountaineering/index.htm"]);
stm_aix("p1i4","p1i0",[0,"绳结技术","","",-1,-1,0,"/SJTUoutdoor/freebag/knowledge/knot/index.htm"]);
stm_ep();
stm_aix("p0i2","p0i1",[0,"    户外装备     ","","",-1,-1,0,"/SJTUoutdoor/freebag/equipment/index.htm"]);
stm_bpx("p2","p1",[]);
stm_aix("p2i0","p1i0",[0,"帐篷","","",-1,-1,0,"/SJTUoutdoor/freebag/equipment/tent/index.htm"]);
stm_aix("p2i1","p1i0",[0,"背包","","",-1,-1,0,"/SJTUoutdoor/freebag/equipment/bag/index.htm"]);
stm_aix("p2i2","p1i0",[0,"睡袋","","",-1,-1,0,"/SJTUoutdoor/freebag/equipment/slpsack/index.htm"]);
stm_aix("p2i3","p1i0",[0,"登山鞋","","",-1,-1,0,"/SJTUoutdoor/freebag/equipment/shoes/index.htm"]);
stm_aix("p2i4","p1i0",[0,"其他","","",-1,-1,0,"/SJTUoutdoor/freebag/equipment/others/index.htm"]);
stm_ep();
stm_aix("p0i3","p0i1",[0,"    各地风情    ","","",-1,-1,0,"/SJTUoutdoor/freebag/photo/index.htm"]);
stm_bpx("p3","p1",[]);
stm_aix("p3i0","p1i0",[0,"神农架精彩照片","","",-1,-1,0,"/SJTUoutdoor/freebag/photo/shengnongjia/index.htm"]);
stm_aix("p3i1","p1i0",[0,"清凉峰精彩照片","","",-1,-1,0,"/SJTUoutdoor/freebag/photo/qingliangfeng/index.htm"]);
stm_ep();
stm_aix("p0i4","p0i1",[0,"    开心之旅     ","","",-1,-1,0,"/SJTUoutdoor/freebag/activity/index.htm"]);
stm_bpx("p4","p1",[]);
stm_aix("p4i0","p1i0",[0,"神农架探险","","",-1,-1,0,"/SJTUoutdoor/freebag/activity/shennongjia/index.htm"]);
stm_aix("p4i1","p1i0",[0,"清凉峰之行","","",-1,-1,0,"/SJTUoutdoor/freebag/activity/qingliangfeng/index.htm"]);
stm_ep();
stm_aix("p0i5","p0i1",[0,"    本站专题     ","","",-1,-1,0,"/SJTUoutdoor/freebag/special/index.htm"]);
stm_bpx("p5","p1",[]);
stm_aix("p5i0","p1i0",[0,"第六届德清越野挑战赛","","",-1,-1,0,"/SJTUoutdoor/freebag/special/deqing/index.htm"]);
stm_ep();
stm_aix("p0i6","p0i1",[0,"     关于我们     ","","",-1,-1,0,"/SJTUoutdoor/freebag/xiehui/index.htm"]);
stm_bpx("p6","p1",[]);
stm_aix("p6i0","p1i0",[0,"协会简介","","",-1,-1,0,"/SJTUoutdoor/freebag/xiehui/intro/index.htm"]);
stm_aix("p6i1","p1i0",[0,"章程理念","","",-1,-1,0,"/SJTUoutdoor/freebag/xiehui/constitution/index.htm"]);
stm_aix("p6i2","p1i0",[0,"各项条例","","",-1,-1,0,"/SJTUoutdoor/freebag/xiehui/byelaw/index.htm"]);
stm_aix("p6i3","p1i0",[0,"会员管理系统","","",-1,-1,0,"/SJTUoutdoor/freebag/xiehui/manage/index1.htm"]);
stm_aix("p6i4","p1i0",[0,"协会编年史","","",-1,-1,0,"/SJTUoutdoor/freebag/xiehui/history/index.htm"]);
stm_aix("p6i5","p1i0",[0,"媒体报道","","",-1,-1,0,"/SJTUoutdoor/freebag/xiehui/media/index.htm"]);
stm_ep();
stm_ai("p0i7",[6,1,"#666666","",2,0,0]);
stm_aix("p0i8","p0i0",[0,"     论坛交流     ","","",-1,-1,0,"/SJTUoutdoor/freebag/bbs/index.htm","_blank","","","","",0,0]);
stm_ep();
stm_em();
